# Generated by Django 3.2.9 on 2022-11-17 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=500)),
                ('backdrop_path', models.CharField(max_length=500)),
                ('popularity', models.IntegerField()),
                ('release_date', models.CharField(max_length=100)),
                ('vote_avg', models.IntegerField()),
                ('vote_cnt', models.IntegerField()),
                ('genre', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('users_pick', models.ManyToManyField(related_name='movies_picked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
